# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactus_app', '0002_auto_20170906_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cactus',
            options={'verbose_name_plural': 'cactuses'},
        ),
    ]
