# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactus_app', '0003_auto_20170906_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cactus',
            options={'verbose_name': 'cactus', 'verbose_name_plural': 'cactuses'},
        ),
    ]
