# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus_app', '0005_auto_20170910_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cactus',
            name='img_url',
        ),
        migrations.AddField(
            model_name='cactus',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='cactus_images'),
        ),
    ]
