# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cactus_app', '0008_auto_20170917_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cactus',
            name='cactus_name',
            field=models.CharField(max_length=100, verbose_name='cactus name'),
        ),
        migrations.AlterField(
            model_name='cactus',
            name='flowers',
            field=models.CharField(max_length=100, verbose_name='flowers'),
        ),
        migrations.AlterField(
            model_name='cactus',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='cactus_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cactus',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='cactus',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
